logo_title: 星辉的博客

style: black

favicon: /favicon.ico

#menu:
  # 作品: /project
  # 域名: /domain
  # 友联: /links
  # 关于: /about
  #Github: https://github.com/sanjinhub

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: WcTOnUJ3cyT2CNdgXltPihOK-gzGzoHsz
  appKey: idTHpw0lbly2alTsrRAYLMHw

highlight:
  enable: false
